language: node_js
node_js: "12"

cache:
  yarn: true

stages:
  - Test
  - name: Release
    if: repo = "ivangabriele/dumdum" AND tag IS present

jobs:
  include:
    - stage: Test
      name: Unit Tests v10
      node_js: "10"

    - stage: Test
      name: Unit Tests v12
      node_js: "12"
      # Only report coverage within this job:
      script: ./scripts/ci/run_unit_tests.sh

    - stage: Release
      name: Github Release
      script: skip
      before_deploy:
        - yarn build:release
        - yarn ci:generate:release_notes
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        edge:
          branch: master
        file: ./dumdum-unsigned.zip
        release_notes_file: ./RELEASE_NOTES.md
        on:
          repo: ivangabriele/dumdum
          tags: true

    - stage: Release
      name: NPM Package
      script: skip
      before_deploy:
        - yarn build
      deploy:
        provider: npm
        access: public
        api_key: $NPM_TOKEN
        edge:
          branch: master
        email: ivan.gabriele@gmail.com
        on:
          repo: ivangabriele/dumdum
          tags: true

# Limit branches builds to "master" & "develop" ones:
branches:
  only:
    - develop
    - master

notifications:
  email:
    on_failure: change
    on_success: never
