name: Check

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
      - run: yarn
      - run: yarn test:lint

  unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
      - run: yarn
      - run: yarn test:unit
      - run: yarn codecov
